---
image: natanfelles/php-base

include:
  - template: Security/SAST.gitlab-ci.yml

variables:
  SAST_EXCLUDED_PATHS: guide, tests, vendor

test:php:
  stage: test
  cache:
    paths:
      - build/
      - vendor/
  services:
    - mariadb
  variables:
    MYSQL_HOST: mariadb
    MYSQL_DATABASE: framework-tests
    MYSQL_ROOT_PASSWORD: password
  before_script:
    - composer install
  script:
    - composer normalize --dry-run --indent-size=4 --indent-style=space
    - vendor/bin/php-cs-fixer fix --diff --dry-run --verbose
    - vendor/bin/phpmd src xml phpmd.xml
    - vendor/bin/phpstan analyse -vvv
    - vendor/bin/phpunit --colors=never
    - phpdoc
  artifacts:
    paths:
      - build/coverage/
      - build/docs/
  coverage: '/^\s*Lines:\s*\d+.\d+\%/'

test:php:mysql:
  extends: test:php
  services:
    - name: mysql
      command:
        - --default-authentication-plugin=mysql_native_password
        - --local-infile=true
  variables:
    MYSQL_HOST: mysql
    DB_HOST: mysql

pages:
  stage: deploy
  dependencies:
    - test:php
    - test:php:mysql
  environment:
    name: production
    url: https://aplus-framework.gitlab.io
  script:
    - mkdir public/
    - mv build/coverage/ public/
    - mv build/docs/ public/
  artifacts:
    paths:
      - public/
  only:
    - master
